ADDED: missing new
If `new` is omitted, `this` will point to window and the following error is displayed:

>         this.on('220', function (chunk) {
>             ^
>
> TypeError: this.on is not a function